config/routes.rb
Rails.application.routes.draw do
  #get 'user/index'
  root 'user#index'
  get '/user_new', to:'user#new'
  post '/user_create', to:'user#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if session[:errors] == nil
      session[:errors] = []
    end
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @errors = []
    p 'create!'
    @user = User.new(user_params)
    p @user.name
    p @user.password
    if @user.name == ''
      @errors << '名前を入力してください'
    end
    if @user.password == ''
      @errors << 'パスワードを入力してください'
    end
    if @errors.count == 0
      @user.save
      flash[:mesasge] = '#{@user.name}さんの新規登録に成功しました'
    end
    session[:errors] = @errors
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<h1>ユーザ一覧</h1>
<%= flash[:message]%>
<ul>
    <% session[:errors].each do |error| %>
        <li><%= error %></li>
    <% end %>
</ul>

<% @users.each do |user| %>
    <p><%= user.name %>　　<%= user.password %></p>
<% end %>

<%= link_to '新規ユーザ追加', user_new_path  %>

app/views/user/new.html.erb
<h1>新規ユーザ登録</h1>
<%= form_for @user, url: user_create_path do |f|  %>
    <p>名前<%= f.text_field :name %></p>
    <p>パスワード<%= f.text_field :password %></p>
    <%= f.submit '作成' %>
<% end %>

<%= link_to 'ユーザ一覧へ', root_path %>